### ISSUE TITLE
ECCV metadata

### ISSUE THREAD

**Issue by wkklavis** [Future-Scholars/paperlib#218] opened 2023-03-17 02:37 UTC
When I crawled through ICLR conference articles, the page number and other information in the publication information were missing
![image](https://user-images.githubusercontent.com/67302399/225797268-872df3bb-f987-4b8a-b880-684d5a9e3abc.png)
When I also crawl through ECCV conference articles, the publication information of conference articles varies in different years
![image](https://user-images.githubusercontent.com/67302399/225797488-b2c78f20-6863-4021-9d58-ab70defde345.png)
![image](https://user-images.githubusercontent.com/67302399/225797511-6188bbbc-8bcb-41ac-8556-07af0a8c29c2.png)
Also，when I crawled the ECCV conference articles, the dblp website crawled the publication information incorrectly, but the paperlib was normal
![image](https://user-images.githubusercontent.com/67302399/225797604-b02af850-3ac1-4a97-ae13-e524f6f87ec8.png)

**Comment by GeoffreyChen777** [comment] 2023-03-17 02:45
1) ICLR doesn't provide many publication info such as page numbers etc. If you know where to get this ,pls let me know.

2) different scrapers usually return different publication venues. The metadata of your first ECCV paper: SiamDoGe should be scraped by our official `paperlib` scraper. The second one should be scraped by google scholar etc.?

It's hard to handle ECCV, because it shows varies venue names in different metadata databases.

Could you please share me your scraper list thus I can try to make this better if I find some solutions?

3) I will investigate this paper and fix it.

**Comment by wkklavis** [comment] 2023-03-17 07:25
Thank you for your reply and attention
my scraper list:
![image](https://user-images.githubusercontent.com/67302399/225838468-2d40ff3c-b0b5-4ced-b8ef-a5d92d38972a.png)

The third question. It seems that when using paperlib, I can obtain normal data, but using a dblp scraper does not work

**Comment by GeoffreyChen777** [comment] 2023-03-17 07:27
Thanks, that must be some bugs in the DBLP scraper. I will investigate and fix it.

**Comment by wkklavis** [comment] 2023-03-17 07:30
Sorry to bother you again, it seems that when exporting multiple selected articles, only the first article information will be exported

**Comment by GeoffreyChen777** [comment] 2023-03-17 07:34
It's weird. export to bibtex? or plain text?

**Comment by wkklavis** [comment] 2023-03-17 07:47
When I select several articles at the same time and export them, whether they are bibtex (key) or plain text, the export result is only the first article selected

**Comment by GeoffreyChen777** [comment] 2023-03-17 07:49
What's your OS? Windows? I cannot reproduce it on Mac...

**Comment by GeoffreyChen777** [comment] 2023-03-17 07:51
OK, maybe it's a windows-specific bug. I will try this on Win.

**Comment by wkklavis** [comment] 2023-03-17 07:53
by the way, I would like to ask if the software‘s ctrl+A instruction is normal on the Mac, and all papers on the current page can be selected

**Comment by GeoffreyChen777** [comment] 2023-03-17 07:54
no, select-all is not implemented yet.

**Comment by wkklavis** [comment] 2023-03-17 07:56
ok, thank you so much, so kind of you

**Comment by GeoffreyChen777** [comment] 2023-03-18 01:49
All your issues should be resolved in the new version.

**Closed by GeoffreyChen777** 2023-03-18 01:49 UTC
Labels: electron, enhancement, high priority
