### ISSUE TITLE
[BUG] Cannot delete added rss-feed

### ISSUE THREAD

**Issue by renecotyfanboy** [Future-Scholars/paperlib#425] opened 2024-03-18 19:29 UTC
**Describe the bug**
Hi there, this is a super great app ! Congrats for this, it is really awesome. I'm sorry I already broke it, I tryed to add a rss-feed and gave a wrong url to do this, and now I can't delete it.

**To Reproduce**
1. Go to Feed window
2. Add a feed with name :"Arxiv's Astrophysics" and url:" https://rss.arxiv.org/rss/astroph.QA"
3. Try to update or delete it (update the feed won't work since the url is bad)

**Screenshots or Log**
<img width="239" alt="Capture d’écran 2024-03-18 à 20 25 27" src="https://github.com/Future-Scholars/paperlib/assets/49200287/02a939ce-15d9-4811-b739-c49cec7ae0a9">
<img width="235" alt="Capture d’écran 2024-03-18 à 20 31 02" src="https://github.com/Future-Scholars/paperlib/assets/49200287/0d09bd75-e368-4ef8-8fa1-7a3c887aa739">

**System (please complete 
the following information):**
 - OS: macOS Sonoma 14.4 (23E214)
 - Paperlib Version 3.0.2

**Additional context**
I would be glad to delete it manually if you point me where the files are packed when running this on my system. Anyway, this is super awesome, I will advertise this in my lab for sure

**Comment by GeoffreyChen777** [comment] 2024-03-18 19:38
Hi I can reproduce it. It is a bug! Thanks for reporting this.

I think this bug is caused by the char `'` in the name. Currently please avoid it.

If you wish to delete it manually, you have two options:

1. delete all your database: go to your app library folder you choose, and delete all files related to `.realm`. then reopen Paperlib. Be careful, you will lose all your data in Paperlib.
2. Download the database viewer [here](https://studio-releases.realm.io/v14.1.2), open your database file(should be something like `default.realm` in your library folder) and delete that feed item.

**Comment by GeoffreyChen777** [comment] 2024-03-18 20:23
Hi this has been fixed by #426. Please wait for the next release!

**Closed** 2024-03-18 20:23 UTC
Labels: bug, high-priority
