### ISSUE TITLE
[Feature Request] Windows ARM64 Version Support

### ISSUE THREAD

**Issue by JohanRain** [Future-Scholars/paperlib#560] opened 2024-06-08 15:22 UTC
I am currently using a Surface Pro X for my daily literature reading and management tasks. Unfortunately, I have not found any software that natively supports the ARM64 architecture and meets my needs. As Microsoft is actively promoting ARM64-based personal computers, I believe that adapting this software for the ARM64 architecture could attract a wider user base. Therefore, I would like to ask if the developers have any plans to support ARM64.

**Comment by GeoffreyChen777** [comment] 2024-06-08 15:26
If Electron supports Win arm64, that would be possible and easy.

The problem is that I don't have any windows arm device. Thus, I cannot test that.

To build on win arm. Just modify the build config. I think that would be ok.

If you'd like to try, I can help you.

**Comment by JohanRain** [comment] 2024-06-08 15:47
Of course, I understand that Electron and Node.js currently support the ARM64 architecture. However, I am unsure how to modify the build config specifically. If you could provide some guidance, I would be glad to test it.😀

**Comment by GeoffreyChen777** [comment] 2024-06-08 15:48
I guess you use wechat, so you can add my wechat:

https://share.1password.com/s#9mSjbB5-an8Mhx-AbsRIsPvy2VaHiOufxBHd00n-4i8

**Comment by GeoffreyChen777** [comment] 2024-06-28 14:27
I'm going to close this. Feel free to reopen if you want to discuss further.

**Closed by GeoffreyChen777** 2024-06-28 14:27 UTC
Labels: feature-request, pending
