### ISSUE TITLE
[Feature request] separate reading and done read papers

### ISSUE THREAD

**Issue by PengFoo** [Future-Scholars/paperlib#114] opened 2022-07-21 06:20 UTC
I sometimes will add a bunch of papers into APP, especially when a conf announce their ac papers.  They will mix with the papers I have read in the main view.
So I would like to have a separate view in main view or other solution to easily tell the papers I have read and papers not read yet.
I am using a "TODO"  tag to do this now, but the tag looks a little weird among other paper tags.
Thx!

**Comment by GeoffreyChen777** [comment] 2022-08-11 17:54
Hi @PengFoo , I'm considering about this feature now, but need some suggestions.

The problem is when should a paper be marked as read.

1. Once a paper item is single-clicked.
2. Once a paper item is double-clicked (PDF file is opened).
3. Manually toggle it.

I think none of the above options are optimal.

The reason is that many users in many daily usage cases, they've already read the paper before importing it to Paperlib. If there is an 'unread' mark for each newly imported paper, this may cause unnecessary disturbance to the before-mentioned users.

Now you are using 'TODO tag' to mark unread papers. Did you consider using ‘flag’ or ’folder‘ to mark？

I think it's easy to add a tag/folder to a paper now. You can not only use the editview but also directly drag paper items/PDF files to a tag/folder in the sidebar. I admit that currently removing a tag or folder is a bit inconvenient. Do you think it would be acceptable to use tag/folder to do the read/unread marking if the removal of tags/folders is simplified? For example:
1. add a remove button for each tag/folder in the details panel.
2. add a context menu item for each paper item in the main list.

Thanks!

**Comment by woodwm** [comment] 2022-10-30 12:06
Zotero does not support showing the status of read or unread as well. I use a coloured read tag to do that, which add a small coloured square at the beginning of a item. More generally, showing the status of a paper is useful in the mainView. If we supports showing coloured tags or priority tags in the mainView, I think it is more powerful.

**Comment by GeoffreyChen777** [comment] 2022-10-30 12:08
@woodwm The key question is when should a paper be marked as read. Do you have any suggestions about this?

**Comment by GeoffreyChen777** [comment] 2022-10-30 12:10
Paperlib has a component to show the read/unread status:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/14183213/198877626-09aa00b2-ac64-4080-9b06-34da01347558.png">

But I only enable it in the feed view, I disable it in the library view because I have no idea about when should I show/hide it.

**Comment by woodwm** [comment] 2022-10-30 12:16
If you mean modifying the status of a paper automatically, you may offer several options. 

For me, I add them manually. Unlike emails, which is usually short and need response. For papers, people have different read style. I think supporting showing coloured tags or priority tags meet the need to display the status of a paper in the mainView and easy to identify. People may add "read", "quick_read", "carefully_read" tags. We just need to way to show these information in the mainView clearly.

**Comment by GeoffreyChen777** [comment] 2022-10-30 12:19
@woodwm Ok, let me optimise the tag/folder component first.

**Comment by GeoffreyChen777** [comment] 2024-02-01 10:38
In the 3.0 beta, we have introduced the extension system and the nested folder system.

I believe this feature can be achieved by:
- creating a folder named `unread` / `inbox` or whatever you like.
- to import papers into this folder, you have several options:
  - directly drag your PDFs onto this folder in the sidebar.
  - create a small extension to add all newly imported paper into this folder automatically.
  - we are planning to enhance our browser extension to support importing papers into specific tags/folders. Just wait for it.

I'm closing this issue now, feel free to reopen it if you want to further discuss it.

**Closed by GeoffreyChen777** 2024-02-01 10:38 UTC
Labels: feature-request
